### ISSUE TITLE
Modify FCGI Proxy 

### ISSUE THREAD

**Issue by alexmglover** [fostermadeco/ansible-roles#12]
I ran into an issue where I needed to add an Alias in Apache. I was blocked by the fact that the ProxyPassMatch routes all php requests through the `document_root`. For this project I removed the ProxyPassMatch line and added this:

```
<FilesMatch \.php$>
 SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>
```

Do you see any reason why we can't switch the ProxyPassMatch to SetHandler?

**Comment by likeuntomurphy** [comment]
Merged #13
