### ISSUE TITLE
Mailhog does not always autostart

### ISSUE THREAD

**Issue by adam-winfree** [fostermadeco/ansible-roles#2]
I ran `vagrant halt` on my machine yesterday (to install updates to my computer) and restarted the box today. Mailhog was not running. It was also not recognized as a service (I'm not sure if it should be).
I logged into the virtual machine and ran this to temporarily fix the issue:
`sudo /usr/bin/env /usr/local/bin/mailhog > /dev/null 2>&1 &`

**Comment by likeuntomurphy** [comment]
Mailhog is managed by Supervisor. To verify that it is not running, use `sudo supervisorctl status`. If it is not running, Supervisor needs to be started — it should be enabled by the `enabled: yes` at the end of the “ensure supervisor is enabled” task, but that is apparently returning a false positive.

**Comment by likeuntomurphy** [comment]
There was an Ansible bug that was causing this, but it is fixed in newer versions (I verified with 2.2.2.0). To fix an existing installation after updating Ansible (with `pip install ansible --upgrade`), set `enabled: no` and rerun, then reset `enabled: yes` and run again.
