### ISSUE TITLE
Use official Xenial box

### ISSUE THREAD

**Issue by likeuntomurphy** [fostermadeco/ansible-roles#24]
At long last, a `vagrant` user has been added to the official `ubuntu/xenial64` box (https://bugs.launchpad.net/cloud-images/+bug/1569237).

I did a quick test spinning up a new VM using it instead of `bento/ubuntu-16.04`, and it mostly worked fine. I had to remove the `config.ssh.password` line from the Vagrantfile, which is not that big of a deal because the only place I actually use the password is in my MySQL client so I don’t have to remember the path to the generated private key. However, I also made a provisional change to use my existing private key and copy my public key to the VM — and then I could connect to the database through my client without even specifying a key since the default private key worked. Is it safe to assume everyone has an existing keypair at `~/.ssh/id_rsa{.pub}`?

I would still like to test it with each existing role to suss out any problems, but I’m inclined to make the switch. It would not be necessary to update existing projects — it could be used only for new ones.

Other thoughts and comments welcome.

**Comment by gstjohn** [comment]
@alexmglover I would assume you might have the best insight into the impact of this change. Would you mind reviewing and commenting?

@likeuntomurphy I think it would be a safe assumption that most have a public key. If they don't we should plan to make that a part of our training.

**Comment by likeuntomurphy** [comment]
One complication I encountered today was that the image is only 10GB, and it ran out of space during a provision. I did find the `vagrant-disksize` plugin which allows you to change the size inside the Vagrantfile, and that solved the immediate issue. The plugin itself also had another plugin dependency, so it would add two more required plugins.
