### ISSUE TITLE
document_root undefined

### ISSUE THREAD

**Issue by adam-winfree** [fostermadeco/ansible-roles#3]
https://github.com/fostermadeco/ansible-roles/commit/7000c5dd564822d1d31dc6bb513e12c38cd512df

removing setting the document_root results in the following error on provision:
TASK [lamp : create virtual host file] *****************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'document_root' is undefined"}

**Comment by likeuntomurphy** [comment]
Copy the change from the latest `development-standard` commit:

https://github.com/fostermadeco/development-standard/commit/2a879533bee345b43fbf5485060b553c8afe8b87
