### ISSUE TITLE
Error w/ role elasticsearch-2.x when running Siphon 

### ISSUE THREAD

**Issue by smaida** [fostermadeco/ansible-roles#32]
Trying to stand up Siphon locally. Received the following error after running vagrant up.

    default: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit="default" --inventory-file=/Users/shawnmaida/Sites/siphon/.vagrant/provisioners/ansible/inventory -v ansible/provision.yml
No config file found; using defaults
ERROR! the role 'elasticsearch-2.x' was not found in /Users/shawnmaida/Sites/siphon/ansible/roles:/etc/ansible/roles:/Users/shawnmaida/Sites/siphon/ansible

The error appears to have been in '/Users/shawnmaida/Sites/siphon/ansible/provision.yml': line 8, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - node
      - role: elasticsearch-2.x
        ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by likeuntomurphy** [comment]
This is not a problem with this repository so much as it is one with the documentation for Siphon. You need to install the official Elasticsearch role globally — see https://github.com/fostermadeco/icsc-search/blob/master/README.md#local-testing-setup for instructions.

One thing to note is that, after installing the role, you need to checkout a commit that supports the version of Elasticsearch required by Siphon. For instance, if the current ES version is 5.x, you need to check out 063e2f3f7a59d25f925733b9a8447b0bffd8242c. If the version is 6.x, you shouldn’t need to do anything. I’m not sure of any of the ES requirements in the project, so @StevenMHernandez may have to chime in.

**Comment by smaida** [comment]
Thanks @likeuntomurphy. I should have caught that in the install docs before posting. I'll close this.
