### ISSUE TITLE
Abandon submodule in favor of custom local role path (?)

### ISSUE THREAD

**Issue by likeuntomurphy** [fostermadeco/ansible-roles#7]
Maybe we should abandon adding the ansible-roles submodule and instead keep a copy of the repo locally. We can then configure ansible to use a custom roles path (http://docs.ansible.com/ansible/intro_configuration.html#roles-path) like /opt/foster-made/roles or something. That way we can get them out of each repository and get rid of the git submodule nonsense that has intermittently caused trouble. I think that indirectly answers your question. The roles can just expand and accumulate without regard to their footprint within projects, because they won't be in a project. And perhaps then every role can be updated to use one specific technology (or two or more closely related ones) — and we can add some stack roles (lamp, django) in development-standard that include tasks or roles directly from our local copies, and they could be used (or not) in provision.yml.

**Comment by likeuntomurphy** [comment]
My candidate for location would be `/usr/local/etc/foster-made/ansible/roles`, because it is writable without having to alter any permissions.

We would have to refactor some roles, specifically the ones that accommodate multiple php versions.

**Comment by alexmglover** [comment]
My only concern is people's local ansible/roles directory getting way out of date. Maybe this is more of a documentation and less a process problem?

**Comment by likeuntomurphy** [comment]
See https://github.com/fostermadeco/rokanan.
